version: '3.8'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: hal_taalam_db
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Saif@Password123
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql

  web:
    image: saifaleslam555/hal_taalam:v1
    container_name: hal_taalam_app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__HalTaalamDB=Server=db;Database=HalTaalamDb;User Id=sa;Password=Saif@Password123;TrustServerCertificate=True;Missing Vb Data=True;

volumes:
  mssql_data: